### ISSUE TITLE
unlocked framerate.

### ISSUE THREAD

**Issue by leenattress** [cstoquer/pixelbox#16]
```
exports.update = function () {
  console.time("framerate");
  console.timeEnd("framerate");
};
```

This gives a low ms number, but:
```
exports.update = function () {
  console.time("framerate");
  var x, y;
  for (x = 0; x < 127; x++) {
    for (y = 0; y < 127; y++) {
      pen(random(15) + 1);
      rect(x, y, 2, 2);
    }
  }
  console.timeEnd("framerate");
};
```

seems to give a lower number, but what should the framerate be? is there a timer on `exports.update`? Can I force 30 or 60 fps?

**Comment by cstoquer** [comment]
The number returned by `console.time` is just the execution time of your code between `time` and `timeEnd`. It is not the actual framerate.

The framerate is managed by the browser. Internally, Pixelbox uses `requestAnimationFrame` for the update loop (see implementation [here](https://github.com/cstoquer/pixelbox/blob/master/boostrap.js#L420-L429)). The browser will try to keep the framerate at 60FPS, but if your game code is doing too much, updates can be skipped and framerate can drop.

To see the framerate, you can use the Developer tools: From the developer console, click on the top-right button and navigate to `More tools > Rendering`:

<img width="350" alt="Screen Shot 2020-05-02 at 16 46 38" src="https://user-images.githubusercontent.com/2462139/80858574-f57ed580-8c94-11ea-83ca-bb9a6a0ba5f5.png">

This should open a window with checkboxes: checking the "FPS meter" will display FPS on top of the game window:

<img width="928" alt="Screen Shot 2020-05-02 at 16 41 54" src="https://user-images.githubusercontent.com/2462139/80858626-72aa4a80-8c95-11ea-9f45-eb7fb5db6b22.png">

Finally, for your specific example, I suggest to use WebGL rendering. This will give you a 10x performance increase. WebGL rendering can be activated from Pixelbox editor: open the project settings from `Project > Settings`, navigate to the `Components` tab, and check the `Use WebGL for rendering` checkbox.

**Comment by leenattress** [comment]
Magical, thank you for getting back to me, I really appreciate the help.
