### ISSUE TITLE
Is there existed some downloadable example/demo projects or tutorials?

### ISSUE THREAD

**Issue by winterwolf** [cstoquer/pixelbox#21]
I don't know where to start learning. I downloaded the engine, created an empty project, drew something on the map, run it and I see a black screen. I understand that probably the map needs to be drawn from the script, but I have no any examples, so it is very difficult for me to take the first steps.

**Comment by ojdon** [comment]
You can find some examples here: https://github.com/cstoquer/pixelbox-examples/

**Comment by winterwolf** [comment]
Thank you!
