### ISSUE TITLE
print not working

### ISSUE THREAD

**Issue by BloodDeity** [cstoquer/pixelbox#27]
print(text, [x, y]) is not working, even when i provide x and y it still prints at 0, 0
![image](https://user-images.githubusercontent.com/53614098/142779493-647ac17f-edcc-44e5-9d09-c4282cb2ca42.png)

**Comment by cstoquer** [comment]
Sorry, the documentation is a bit confusing. The braces in the documentation means the parameters are optional.

To print at a specific location, just write: `print('New Game', 10, 100)` without the braces.
